
when:
  - event: push
    branch: main

steps:
  publish:
    image: docker.io/woodpeckerci/plugin-docker-buildx:latest
    settings:
      dockerfile: Dockerfile
      repo: codeberg.org/privau/searxng
      tags: latest
      platforms: linux/amd64
      logins:
        - registry: https://codeberg.org
          username: vojkovic
          password:
            from_secret: cb_token
