
when:
  - event: push
    branch: main

steps:
  publish:
    image: docker.io/woodpeckerci/plugin-docker-buildx:latest
    settings:
      dockerfile: Dockerfile
      repo: codeberg.org/${CI_REPO_OWNER}/searxng
      registry: codeberg.org
      tags: latest
      platforms: linux/amd64
      username: vojkovic
      password:
        from_secret: cb_token
