
when:
  - event: push
    branch: main

steps:
  publish:
    image: docker.io/woodpeckerci/plugin-kaniko:2.3.2
    settings:
      dockerfile: Dockerfile
      registry: https://codeberg.org
      repo: privau/searxng
      tags: latest
      username: vojkovic
      password:
        from_secret: cb_token
