# Using Cloudflare tunnels to host SearXNG instance
services:
  searxng:
    build: .
    networks:
      - proxy
    restart: always
    environment:
      BASE_URL: https://searxng.admingod.ch/
      MORTY_URL: https://searxng.admingod.ch/
      INSTANCE_NAME: SearXNG
      AUTOCOMPLETE: ""  # Temporarily disable autocomplete until properly configured
      # Public instance settings
      PUBLIC_INSTANCE: true
      CONTACT: https://admingod.ch
      GIT_URL: https://github.com/AdminGodZ/searxng
      # Redis configuration for rate limiting
      REDIS_URL: redis://redis:6379/0
      LIMITER: true
    depends_on:
      - redis

  redis:
    image: redis:alpine
    networks:
      - proxy
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

networks:
  proxy:
    external: true

volumes:
  redis_data:
